services:
  backend:
    image: kgruca7747/courseflow-backend
    ports:
      - "4000:4000"
    working_dir: &PROJECT_ROOT_DIR /app
    volumes:
      # mount cached vscode container extensions
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode-extensions:/home/development/.vscode-server/extensions
      - vscode-extensions-insiders:/home/development/.vscode-server-insiders/extensions

      # https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
      # keep user development .bash_history between container restarts
      - bash-history:/home/development/commandhistory

    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "CourseFlow"
      DATABASE_URL: "postgresql://postgres:dbpass@postgres:5432/CourseFlow?schema=public"
      REDIS_URL: "redis://redis:6379"
      # optional: project root directory, used for relative path resolution (e.g. fixtures)
      PROJECT_ROOT_DIR: *PROJECT_ROOT_DIR

      # optional: enable pretty print of log output
      # intended use is for development and debugging purposes only
      # not recommended to enable on production systems due to performance penalty and loss of parsing ability
      SERVER_LOGGER_PRETTY_PRINT_CONSOLE: "true"

  postgres:
    image: postgres:latest
    # ATTENTION
    # fsync=off, synchronous_commit=off and full_page_writes=off
    # gives us a major speed up during local development and testing (~30%),
    # however you should NEVER use these settings in PRODUCTION unless
    # you want to have CORRUPTED data.
    # DO NOT COPY/PASTE THIS BLINDLY.
    # YOU HAVE BEEN WARNED.
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "dbpass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "CourseFlow"
    volumes:
      - pgvolume:/var/lib/postgresql/data
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql # Mount the SQL dump file

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  frontend:
    image: kgruca7747/courseflow-web
    expose:
      - "3000"
    ports:
      - "80:3000"

volumes:
  # postgresql: declare a named volume to persist DB data
  pgvolume:

  # vscode: Avoiding extension reinstalls on container rebuild
  # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
  vscode-extensions:
  vscode-extensions-insiders:

  # https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
  bash-history:
