### Register a new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "JakubTTT@example.com",
  "password": "password123",
  "firstName": "Marcin",
  "lastName": "Dudek"
}
### Register a new user
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test@testowy.pl",
  "password": "123"
}

### Get user data (requires authentication)
# Replace the token below with a valid token received from login or register
GET http://localhost:4000/api/auth/me
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..lPQKxngXlWWDdaTj.LNGNjGLswlPxQ68W6q7sHL8BuN8BMzhWEZBHVz4JiuJ_wN-LBCwiDyZ3ZBjSYkQ7ICDTYO0tdbsH-PbU0VJB13D1rxo8tXYH2fiPmzad23q1Tea27YgXlFeULrbRt3LD9xGs493DZXrY24XdDN1oN_CB_dnTEXt7Q1ykjWMx1pCS4Z8.6cyx672l3zwlqQLk7_E_jw
Content-Type: application/json

### Get all users (requires admin authentication)
GET http://localhost:4000/api/admin/users
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

### Change user role (requires admin authentication)
PUT http://localhost:4000/api/admin/users/1/role
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

{
  "role": "user"
}
### Delete user from database (requires admin authentication)

DELETE http://localhost:4000/api/admin/users/1
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

### GET ROLES FROM DATABASE (requires admin authentication)
GET http://localhost:4000/api/role/getrole
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..OCuHzO-3fgi6mQ5E.QZv1DSv3EsucZD6EyI9z3LWA01A7Xp8UaE2l1Whibt_3BAUc7YT-d5B_3eiKZ5M7m87WkLsZl3JSDZx7iWRY3vBZzO4oxhoyds1SnZHs-9aShIwz0figDsg9y84lEQAUe8iUHTV92v1Ln4ycCpYzSR8n_vYYSDY_UaJ2wmaWH6zqzhhs.y21ZJyq4LaXInqpC3rkIOg
Content-Type: application/json

### Update Role (requires admin authentication)
PATCH http://localhost:4000/api/role/updaterole/1
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..BR_P17xhHHN8NAtZ.FsBzcYTxuZ33rZjdjDyRzxAsq-9bBraFbLuzGG3Fo4wnEkBY7im4uO0KD85mB5Ue5mDVQ3maw5mvX8m4i8Shy2TGG0LhGe2OlIubGyzjSG4twQZ9XdXhl2Ap5KNkXzWcXmkpTCMak92zzXBpFXQFke3QSKQ6Jw5P8Kcc4YHfhCv2hZ0.49UHQpSFcKSQm4DsbALZ7g
Content-Type: application/json

{
  "roleName": "admin",
  "permissions": [4,6,7,8,9,10 ]
}

### Tworzenie kursu
POST http://localhost:4000/api/courses
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..kIjnfOb_hw2gQ7kB.CMBveJxlsVtTibcgjSSdklxJWgBvkB5NCDKt_KPJUdONIIcZf6ylzP3Vet2P30Oy7Zuqj4obmEXEd7XjUfm_0-oQt-i-jC-B6HhG6bem4GMnx-rcUcoKBl-GNppiNBW9oJw_zZgoeWgppd7AcupaEZH9jnU50vBWSbs_zeb0uhoMEGXG.YJWea7WIaSXXnljh3siEmQ
Content-Type: application/json

{
  "title": "React dla początkujących",
  "category": "Programowanie",
  "description": "Podstawowy kurs Reacta dla osób, które dopiero zaczynają."
}


### Pobieranie wszystkich kursów
GET http://localhost:4000/api/courses
Content-Type: application/json

### Pobieranie pojedynczego kursu 
GET http://localhost:4000/api/courses/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SXUhoXSlNG6YKhys.qwp1oY02Wir3Ld2pBwOZrxp3Z-LG4YJ5gW2CZK9p-CfTy-wHfwgy-fyEKtMBrS6BW076VpOp9PL4y5X5fUf_KWJTwWa7rhz_L1_Kttt4sD0YgXrdAnQoyP0swHPD3aYt5lZKN2gK5HI3fg0hXtLkyGDetskXhV-oi41luD03J-OGbgPu.0bvB5sPi5-SDXnrxhcVhfQ

### Aktualizacja kursu
PATCH http://localhost:4000/api/courses/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SXUhoXSlNG6YKhys.qwp1oY02Wir3Ld2pBwOZrxp3Z-LG4YJ5gW2CZK9p-CfTy-wHfwgy-fyEKtMBrS6BW076VpOp9PL4y5X5fUf_KWJTwWa7rhz_L1_Kttt4sD0YgXrdAnQoyP0swHPD3aYt5lZKN2gK5HI3fg0hXtLkyGDetskXhV-oi41luD03J-OGbgPu.0bvB5sPi5-SDXnrxhcVhfQ

{
  "title": "Test Endpointu do akutalizacji",
  "category": "Programowanie",
  "description": "Podstawowy kurs Reacta dla osób, które dopiero zaczynają."
}
