### Register a new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "JakubTTT@example.com",
  "password": "password123",
  "firstName": "Marcin",
  "lastName": "Dudek"
}
### Register a new user
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test@testowy.pl",
  "password": "123"
}

### Get user data (requires authentication)
# Replace the token below with a valid token received from login or register
GET http://localhost:4000/api/auth/me
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..lPQKxngXlWWDdaTj.LNGNjGLswlPxQ68W6q7sHL8BuN8BMzhWEZBHVz4JiuJ_wN-LBCwiDyZ3ZBjSYkQ7ICDTYO0tdbsH-PbU0VJB13D1rxo8tXYH2fiPmzad23q1Tea27YgXlFeULrbRt3LD9xGs493DZXrY24XdDN1oN_CB_dnTEXt7Q1ykjWMx1pCS4Z8.6cyx672l3zwlqQLk7_E_jw
Content-Type: application/json

### Get all users (requires admin authentication)
GET http://localhost:4000/api/admin/users
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

### Change user role (requires admin authentication)
PUT http://localhost:4000/api/admin/users/1/role
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

{
  "role": "user"
}
### Delete user from database (requires admin authentication)

DELETE http://localhost:4000/api/admin/users/1
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..bRYtPhzo7BYSw3_z.fX71tzU989snbO2zB0V5fw31pA9-gyD2BzrS4k66VK1-we2Y0GZTy5pnM_yRusruybtDyCiclgXthvaNWhy2hFb7S4JfrUXbcyYms4D1dUgBwtMGoHtEQnlwZvtxWhdS377yKIKrMGRryqghT7BkUo3WC5BzvuMZBwoQFiArnbJC8Qk.aHc2ngX9fY3ntRUAJjgx_Q
Content-Type: application/json

### GET ROLES FROM DATABASE (requires admin authentication)
GET http://localhost:4000/api/role/getrole
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..v8zFw0CzIBbGYKxB.komag-Ibm4h7uLVk-ax7dOU10CMXwp-Zt4oPDxXEX32QVD4RRHEOLm6KthNi4vt6tAzejmXcs-R9ARyfX7_VKlciTAG2ZBnTLk9PCCD-P8bwnmZwO_WoXYuo_UAyCY5bIckWRQFDtC0R0BsKAR6Fu4cqyAeIR6CdrjxRizLHLEJp3-13.Qyz20t_6wsbB-MOhdRAQ8w
Content-Type: application/json

### Update Role (requires admin authentication)
PATCH http://localhost:4000/api/role/updaterole/1
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..BR_P17xhHHN8NAtZ.FsBzcYTxuZ33rZjdjDyRzxAsq-9bBraFbLuzGG3Fo4wnEkBY7im4uO0KD85mB5Ue5mDVQ3maw5mvX8m4i8Shy2TGG0LhGe2OlIubGyzjSG4twQZ9XdXhl2Ap5KNkXzWcXmkpTCMak92zzXBpFXQFke3QSKQ6Jw5P8Kcc4YHfhCv2hZ0.49UHQpSFcKSQm4DsbALZ7g
Content-Type: application/json

{
  "roleName": "admin",
  "permissions": [4,6 ]
}

